name: Release ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  release-job:
    permissions:
      issues: write
      contents: write
      packages: write
      repository-projects: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Install nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "ok"
    - name: Install semantic
      run: |
        npm i -g semantic-release
        npm i -g @semantic-release/changelog
        npm i -g @semantic-release/github
        npm i -g @semantic-release/exec
        npm i -g @semantic-release/git
        npm i -g @semantic-release/release-notes-generator
    - name: Test push
      run: |
        git fetch
        git config --global user.email "tkhadir.dev@gmail.com"
        git config --global user.name "tkhadir"
        echo "hello world" >> test.txt
        git add test.txt
        git commit -m "feat: add test"
        git push origin
    - name: Run semantic
      run: semantic-release --no-ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
